version: '3.5'

services:
  app:
    build: ./app
    links:
      - db
    ports:
      - 8080:5000
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PASS: root

  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
